version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  celery:
    build: .
    command: celery -A DevelopsTodayTask worker -l info
    volumes:
      - .:/code
  celery-beat:
    build: .
    command: celery -A DevelopsTodayTask beat -l info
    volumes:
      - .:/code

