# Generated by Django 3.2 on 2021-04-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_board', '0002_auto_20210427_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
