# Generated by Django 3.2 on 2021-04-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_board', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
    ]
